#ROUTING DEL GESOBJESPBUNDLE
MinSalSidPlaGesObjEspBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:Default:index }

MinSalSidPlaGesObjEspBundle_consultarObjetivosEspecificos:
    pattern:  /consultarObjetivosEspecificos
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminObjetivosEspecificos:consultarObjetivosEspecificos }


MinSalSidPlaGesObjEspBundle_consultarObjetivosEspecificosJSON:
    pattern:  /consultarObjetivosEspecificosJSON
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminObjetivosEspecificos:consultarObjetivosEspecificosJSON}

MinSalSidPlaGesObjEspBundle_manttObjetivosEspecificos:
    pattern:  /manttObjetivosEspecificos
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminObjetivosEspecificos:manttObjetivosEspecificos}

MinSalSidPlaGesObjEspBundle_consultarResultadosEsperados:
    pattern:  /consultarResultadosEsperados
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminResultadosEsperados:consultarResultadosEsperados}

MinSalSidPlaGesObjEspBundle_consultarResultadosEsperadosJSON:
    pattern:  /consultarResultadosEsperadosJSON
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminResultadosEsperados:consultarResultadosEsperadosJSON}

MinSalSidPlaGesObjEspBundle_manttResultadosEsperados:
    pattern:  /manttResultadosEsperados
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminResultadosEsperados:manttResultadosEsperados}

MinSalSidPlaGesObjEspBundle_ingresoResultadosEsperados:
    pattern:  /ingresoResultadosEsperados
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminResultadosEsperados:ingresoResultadosEsperados}

MinSalSidPlaGesObjEspBundle_guardarResultadosEsperados:
    pattern:  /guardarResultadosEsperados
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminResultadosEsperados:guardarResultadosEsperados}


MinSalSidPlaGesObjEspBundle_consultarTipoMeta:
    pattern:  /consultarTipoMeta
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminResultadosEsperados:consultarTipoMeta}

MinSalSidPlaGesObjEspBundle_editarResultadosEsperados:
    pattern:  /editarResultadosEsperados
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminResultadosEsperados:editarResultadosEsperados}
MinSalSidPlaGesObjEspBundle_editandoResultadosEsperados:
    pattern:  /editandoResultadosEsperados
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminResultadosEsperados:editandoResultadosEsperados}

MinSalSidPlaGesObjEspBundle_consultarActividades:
    pattern:  /consultarActividades
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminActividades:consultarActividades}

MinSalSidPlaGesObjEspBundle_consultarActividadesJSON:
    pattern:  /consultarActividadesJSON
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminActividades:consultarActividadesJSON}

MinSalSidPlaGesObjEspBundle_ingresoActividades:
    pattern:  /ingresoActividades
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminActividades:ingresoActividades}
   
MinSalSidPlaGesObjEspBundle_guardarActividades:
    pattern:  /guardarActividades
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminActividades:guardarActividades}
    
MinSalSidPlaGesObjEspBundle_editarActividad:
    pattern:  /editarActividad
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminActividades:editarActividad}
    
MinSalSidPlaGesObjEspBundle_editandoActividades:
    pattern:  /editandoActividades
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminActividades:editandoActividades}

MinSalSidPlaGesObjEspBundle_gestionVinculacion:
    pattern:  /gestionarVinculacion
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminVinculacionActividades:gestionVinculacion}

MinSalSidPlaGesObjEspBundle_agregarVinculacion:
    pattern:  /agregarVinculacion
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminVinculacionActividades:agregarVinculacion}
    
    