#ROUTING DEL GESOBJESPBUNDLE
MinSalSidPlaGesObjEspBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:Default:index }

#OBJETIVOESPECIFIGO
MinSalSidPlaGesObjEspBundle_consultarObjetivosEspecificos:
    pattern:  /consultarObjetivosEspecificos
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminObjetivosEspecificos:consultarObjetivosEspecificos }

MinSalSidPlaGesObjEspBundle_manttObjetivosEspecificos:
    pattern:  /manttObjetivosEspecificos
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminObjetivosEspecificos:manttObjetivosEspecificos}

MinSalSidPlaGesObjEspBundle_ingresarObjetivoEspecifico:
    pattern:  /ingresarObjetivoEspecifico
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminObjetivosEspecificos:ingresarObjetivoEspecifico}

MinSalSidPlaGesObjEspBundle_editarObjetivoEspecifico:
    pattern:  /editarObjetivoEspecifico
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminObjetivosEspecificos:editarObjetivoEspecifico}

#RESULTADOESPERADO
MinSalSidPlaGesObjEspBundle_consultarResultadosEsperados:
    pattern:  /consultarResultadosEsperados
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminResultadosEsperados:consultarResultadosEsperados}

MinSalSidPlaGesObjEspBundle_manttResultadosEsperados:
    pattern:  /manttResultadosEsperados
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminResultadosEsperados:manttResultadosEsperados}

MinSalSidPlaGesObjEspBundle_ingresoResultadosEsperados:
    pattern:  /ingresoResultadosEsperados
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminResultadosEsperados:ingresoResultadosEsperados}

MinSalSidPlaGesObjEspBundle_guardarResultadosEsperados:
    pattern:  /guardarResultadosEsperados
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminResultadosEsperados:guardarResultadosEsperados}


MinSalSidPlaGesObjEspBundle_consultarTipoMeta:
    pattern:  /consultarTipoMeta
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminResultadosEsperados:consultarTipoMeta}

MinSalSidPlaGesObjEspBundle_editarResultadosEsperados:
    pattern:  /editarResultadosEsperados
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminResultadosEsperados:editarResultadosEsperados}
MinSalSidPlaGesObjEspBundle_editandoResultadosEsperados:
    pattern:  /editandoResultadosEsperados
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminResultadosEsperados:editandoResultadosEsperados}

#ACTIVIDADES
MinSalSidPlaGesObjEspBundle_consultarActividades:
    pattern:  /consultarActividades
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminActividades:consultarActividades}

MinSalSidPlaGesObjEspBundle_ingresoActividades:
    pattern:  /ingresoActividades
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminActividades:ingresoActividades}
   
MinSalSidPlaGesObjEspBundle_guardarActividades:
    pattern:  /guardarActividades
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminActividades:guardarActividades}
    
MinSalSidPlaGesObjEspBundle_editarActividad:
    pattern:  /editarActividad
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminActividades:editarActividad}
    
MinSalSidPlaGesObjEspBundle_editandoActividades:
    pattern:  /editandoActividades
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminActividades:editandoActividades}

#ACTIVIDADVINCULADA
MinSalSidPlaGesObjEspBundle_gestionVinculacion:
    pattern:  /gestionarVinculacion
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminVinculacionActividades:gestionVinculacion}

MinSalSidPlaGesObjEspBundle_agregarVinculacion:
    pattern:  /agregarVinculacion
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminVinculacionActividades:agregarVinculacion}

MinSalSidPlaGesObjEspBundle_obtenerActividadesJSON:
    pattern:  /obtenerActividadesJSON
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminVinculacionActividades:obtenerActividadesJSON}

MinSalSidPlaGesObjEspBundle_vincularActividades:
    pattern:  /vincularActividades
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminVinculacionActividades:vincularActividades}

MinSalSidPlaGesObjEspBundle_obtenerActividadesVincJSON:
    pattern:  /obtenerActividadesVincJSON
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminVinculacionActividades:obtenerActividadesVincJSON}

MinSalSidPlaGesObjEspBundle_desvincularActividades:
    pattern:  /desvincularActividades
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminVinculacionActividades:desvincularActividades}

MinSalSidPlaGesObjEspBundle_agregarVinculacionDependencias:
    pattern:  /agregarVinculacionDependencias
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminVinculacionActividades:agregarVinculacionDependencias}

MinSalSidPlaGesObjEspBundle_consultarUnidadesDependenciasJSON:
    pattern:  /consultarUnidadesDependenciasJSON
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminVinculacionActividades:consultarUnidadesDependenciasJSON}

MinSalSidPlaGesObjEspBundle_aprobarVinculacion:
    pattern:  /aprobarVinculacion
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminVinculacionActividades:aprobarVinculacion}

MinSalSidPlaGesObjEspBundle_obtenerActividadesVincDependicentesJSON:
    pattern:  /obtenerActividadesVincDependicentesJSON
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminVinculacionActividades:obtenerActividadesVincDependicentesJSON}

MinSalSidPlaGesObjEspBundle_mostrarActDependendientes:
    pattern:  /mostrarActDependendientes
    defaults: { _controller: MinSalSidPlaGesObjEspBundle:AccionAdminVinculacionActividades:mostrarActDependendientes}



