#ROUTING DE DEPUNIBUNDLE
MinSalSidPlaDepUniBundle_principal:
    pattern:  /principal
    defaults: { _controller: MinSalSidPlaDepUniBundle:Default:principal }

#TIPORRHUMANO
MinSalSidPlaDepUniBundle_mantenimientoTipoRecurso:
    pattern:  /mantenimientoTipoRecurso
    defaults: { _controller: MinSalSidPlaDepUniBundle:AccionDepUniTipoRRHH:mantenimientoTipoRecurso }
    
MinSalSidPlaDepUniBundle_consultarTipoRRHHJSON:
    pattern:  /consultarTipoRRHHJSON
    defaults: { _controller: MinSalSidPlaDepUniBundle:AccionDepUniTipoRRHH:consultarTipoRRHHJSON }
    
MinSalSidPlaDepUniBundle_manttTipoRRHHEdicion:
    pattern:  /manttTipoRRHHEdicion
    defaults: { _controller: MinSalSidPlaDepUniBundle:AccionDepUniTipoRRHH:manttTipoRRHHEdicion }

#DEPARTAMENTOUNI
MinSalSidPlaDepUniBundle_consultarDeptoUniJSON:
    pattern:  /consultarDeptoUniJSON
    defaults: { _controller: MinSalSidPlaDepUniBundle:AccionDepUniDeptoUni:consultarDeptoUniJSON }
    
MinSalSidPlaDepUniBundle_manttDeptoUniEdicion:
    pattern:  /manttDeptoUniEdicion
    defaults: { _controller: MinSalSidPlaDepUniBundle:AccionDepUniDeptoUni:manttDeptoUniEdicion }

#RECURSOHUMANO
MinSalSidPlaDepUniBundle_consultarRRHHJSON:
    pattern:  /consultarRRHHJSON
    defaults: { _controller: MinSalSidPlaDepUniBundle:AccionDepUniRRHH:consultarRRHHJSON}

MinSalSidPlaDepUniBundle_manttRRHHEdicion:
    pattern:  /manttRRHHEdicion
    defaults: { _controller: MinSalSidPlaDepUniBundle:AccionDepUniRRHH:manttRRHHEdicion}
    
