parameters:
#    min_sal_sid_pla_indicadores_template.example.class: MinSal\SidPla\IndicadoresTemplateBundle\Example

services:
#    min_sal_sid_pla_indicadores_template.example:
#        class: %min_sal_sid_pla_indicadores_template.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
