#ROUNTING DEL GesObjEspEntControlBundle
MinSalSidPlaGesObjEspEntControlBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:Default:index }

#ObjespTemplate
MinSalSidPlaGesObjEspEntControlBundle_consultarObjetivosEspecificosTemplate:
    pattern:  /consultarObjetivosEspecificosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:consultarObjetivosEspecificosTemplate }

MinSalSidPlaGesObjEspEntControlBundle_consultarObjetivosEspecificosTemplateJSON:
    pattern:  /consultarObjetivosEspecificosTemplateJSON
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:consultarObjetivosEspecificosTemplateJSON }

MinSalSidPlaGesObjEspEntControlBundle_manttObjetivosEspecificosTemplate:
    pattern:  /manttObjetivosEspecificosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:manttObjetivosEspecificosTemplate }



