#ROUNTING DEL GesObjEspEntControlBundle
MinSalSidPlaGesObjEspEntControlBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:Default:index }

#ObjespTemplate
MinSalSidPlaGesObjEspEntControlBundle_consultarObjetivosEspecificosTemplate:
    pattern:  /consultarObjetivosEspecificosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:consultarObjetivosEspecificosTemplate }

MinSalSidPlaGesObjEspEntControlBundle_consultarObjetivosEspecificosTemplateJSON:
    pattern:  /consultarObjetivosEspecificosTemplateJSON
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:consultarObjetivosEspecificosTemplateJSON }

MinSalSidPlaGesObjEspEntControlBundle_manttObjetivosEspecificosTemplate:
    pattern:  /manttObjetivosEspecificosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:manttObjetivosEspecificosTemplate }


#ResultadosTemplate
MinSalSidPlaGesObjEspEntControlBundle_consultarResultadosEsperadosTemplate:
    pattern:  /consultarResultadosEsperadosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminResultadosEsperadosTemplate:consultarResultadosEsperadosTemplate }

MinSalSidPlaGesObjEspEntControlBundle_consultarResultadosEsperadosTemplateJSON:
    pattern:  /consultarResultadosEsperadosTemplateJSON
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminResultadosEsperadosTemplate:consultarResultadosEsperadosTemplateJSON }

MinSalSidPlaGesObjEspEntControlBundle_manttObjetivosEspecificosTemplate:
    pattern:  /manttObjetivosEspecificosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminResultadosEsperadosTemplate:manttObjetivosEspecificosTemplate }

MinSalSidPlaGesObjEspEntControlBundle_ingresoResultadosEsperadosTemplate:
    pattern:  /ingresoResultadosEsperadosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminResultadosEsperadosTemplate:ingresoResultadosEsperadosTemplate }

