#ROUNTING DEL GesObjEspEntControlBundle
MinSalSidPlaGesObjEspEntControlBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:Default:index }

#OBJETIVOS TEMPLATE
MinSalSidPlaGesObjEspEntControlBundle_consultarObjetivosEspecificosTemplate:
    pattern:  /consultarObjetivosEspecificosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:consultarObjetivosEspecificosTemplate }
MinSalSidPlaGesObjEspEntControlBundle_consultarObjetivosEspecificosTemplateJSON:
    pattern:  /consultarObjetivosEspecificosTemplateJSON
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:consultarObjetivosEspecificosTemplateJSON }    
MinSalSidPlaGesObjEspEntControlBundle_ingresarObjEspTemplate:
    pattern:  /ingresarObjEspTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:ingresarObjEspTemplate } 
MinSalSidPlaGesObjEspEntControlBundle_editarObjEspTemplate:
    pattern:  /editarObjEspTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:editarObjEspTemplate}
MinSalSidPlaGesObjEspEntControlBundle_manttObjEspTemplate:
    pattern:  /manttObjEspTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:manttObjEspTemplate }

#RESULTADOS ESPERADOS
MinSalSidPlaGesObjEspEntControlBundle_consultarResultadosEsperadosTemplate:
    pattern:  /consultarResultadosEsperadosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminResultadosEsperadosTemplate:consultarResultadosEsperadosTemplate }
MinSalSidPlaGesObjEspEntControlBundle_consultarResultadosEsperadosTemplateJSON:
    pattern:  /consultarResultadosEsperadosTemplateJSON
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminResultadosEsperadosTemplate:consultarResultadosEsperadosTemplateJSON }
MinSalSidPlaGesObjEspEntControlBundle_ingresoResultadosEsperadosTemplate:
    pattern:  /ingresoResultadosEsperadosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminResultadosEsperadosTemplate:ingresoResultadosEsperadosTemplate }
