#ROUNTING DEL GesObjEspEntControlBundle
MinSalSidPlaGesObjEspEntControlBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:Default:index }

#OBJETIVOS TEMPLATE
MinSalSidPlaGesObjEspEntControlBundle_consultarObjetivosEspecificosTemplate:
    pattern:  /consultarObjetivosEspecificosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:consultarObjetivosEspecificosTemplate }
MinSalSidPlaGesObjEspEntControlBundle_ingresarObjEspTemplate:
    pattern:  /ingresarObjEspTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:ingresarObjEspTemplate } 
MinSalSidPlaGesObjEspEntControlBundle_editarObjEspTemplate:
    pattern:  /editarObjEspTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:editarObjEspTemplate}
MinSalSidPlaGesObjEspEntControlBundle_manttObjEspTemplate:
    pattern:  /manttObjEspTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:manttObjEspTemplate }

MinSalSidPlaGesObjEspEntControlBundle_manttObjEspTemplatedos:
    pattern:  /manttObjEspTemplatedos
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:manttObjEspTemplatedos }
    
MinSalSidPlaGesObjEspEntControlBundle_crearPlantilla:
    pattern:  /crearPlantilla
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminObjetivosEspecificosTemplate:crearPlantilla }

#RESULTADOS ESPERADOS
MinSalSidPlaGesObjEspEntControlBundle_consultarResultadosEsperadosTemplate:
    pattern:  /consultarResultadosEsperadosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminResultadosEsperadosTemplate:consultarResultadosEsperadosTemplate }
MinSalSidPlaGesObjEspEntControlBundle_ingresoResultadosEsperadosTemplate:
    pattern:  /ingresoResultadosEsperadosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminResultadosEsperadosTemplate:ingresoResultadosEsperadosTemplate }

MinSalSidPlaGesObjEspEntControlBundle_guardarResultadosEsperadosTemplate:
    pattern:  /guardarResultadosEsperadosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminResultadosEsperadosTemplate:guardarResultadosEsperadosTemplate }

MinSalSidPlaGesObjEspEntControlBundle_editarResultadosEsperadosTemplate:
    pattern:  /editarResultadosEsperadosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminResultadosEsperadosTemplate:editarResultadosEsperadosTemplate }

MinSalSidPlaGesObjEspEntControlBundle_editandoResultadosEsperadosTemplate:
    pattern:  /editandoResultadosEsperadosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminResultadosEsperadosTemplate:editandoResultadosEsperadosTemplate }

MinSalSidPlaGesObjEspEntControlBundle_manttResultadosEsperadosTemplate:
    pattern:  /manttResultadosEsperadosTemplate
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionAdminResultadosEsperadosTemplate:manttResultadosEsperadosTemplate }

#DE ENTIDADES DE CONTROL
MinSalSidPlaGesObjEspEntControlBundle_consultarObjetivosEspecificos:
    pattern:  /consultarObjetivosEspecificos
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionObjetivosUnidadControl:consultarObjetivosEspecificos }

MinSalSidPlaGesObjEspEntControlBundle_consultarResultadosEsperados:
    pattern:  /consultarResultadosEsperados
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionResultEspeEntControl:consultarResultadosEsperados }

MinSalSidPlaGesObjEspEntControlBundle_consultarObjetivosEspecificosEntControl:
    pattern:  /consultarObjetivosEspecificosEntControl
    defaults: { _controller: MinSalSidPlaGesObjEspEntControlBundle:AccionObjetivosUnidadControl:consultarObjetivosEspecificosEntControl }



