parameters:
#    min_sal_sid_pla_ges_obj_esp_ent_control.example.class: MinSal\SidPla\GesObjEspEntControlBundle\Example

services:
#    min_sal_sid_pla_ges_obj_esp_ent_control.example:
#        class: %min_sal_sid_pla_ges_obj_esp_ent_control.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
