MinSalSidPlaReportesBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:index }

#PAOCONTROLLER
MinSalSidPlaReportesBundle_reporteJustificacion:
    pattern:  /reportjustificacion
    defaults: { _controller: MinSalSidPlaReportesBundle:Pao:reporteJustificacion }
    
#ESTADOINFRAESTRUCTURACONTROLLER
MinSalSidPlaReportesBundle_reporteInfraEvaluada:
    pattern:  /reporteInfraEvaluada
    defaults: { _controller: MinSalSidPlaReportesBundle:EstadoInfraestructura:reporteInfraEvaluada }
    
MinSalSidPlaReportesBundle_reporteElementoInfra:
    pattern:  /reporteElementoInfra
    defaults: { _controller: MinSalSidPlaReportesBundle:EstadoInfraestructura:reporteElementoInfra }

#DEFAULTCONTROLLER
MinSalSidPlaReportesBundle_reporteActividadesAtrasadas:
    pattern:  /reporteActividadesAtrasadas
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:reporteActividadesAtrasadas }    
#INFORMACION GERNERAL UNIDAD ORGA    
MinSalSidPlaReportesBundle_reporteInfoGeneral:
    pattern:  /reporteInfoGeneral
    defaults: { _controller: MinSalSidPlaReportesBundle:Admin:reporteInfoGeneral } 
     
MinSalSidPlaReportesBundle_reporteConsolidadoNivelCentral:
    pattern:  /reporteConsolidadoNivelCentral
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:reporteConsolidadoNivelCentral } 

#ACCIONCONSOLIDADOSNIVELCENTRAL
MinSalSidPlaReportesBundle_showConsolidadosNivelCentral:
    pattern:  /showConsolidadosNivelCentral
    defaults: { _controller: MinSalSidPlaReportesBundle:AccionConsolidadosNivelCentral:showConsolidadosNivelCentral } 
    
#REPORTE EMPLEADOS DE UNIDADES ORG  
MinSalSidPlaReportesBundle_reporteEmpleadosOrg:
    pattern:  /reporteEmpleadosOrg
    defaults: { _controller: MinSalSidPlaReportesBundle:Admin:reporteEmpleadosOrg} 