MinSalSidPlaReportesBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:index }
MinSalSidPlaReportesBundle_reporteJustificacion:
    pattern:  /reportjustificacion
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:reporteJustificacion }  
    
MinSalSidPlaReportesBundle_reporteActividadesAtrasadas:
    pattern:  /reporteActividadesAtrasadas
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:reporteActividadesAtrasadas }     
