MinSalSidPlaReportesBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:index }

#PAOCONTROLLER
MinSalSidPlaReportesBundle_reporteJustificacion:
    pattern:  /reportjustificacion
    defaults: { _controller: MinSalSidPlaReportesBundle:Pao:reporteJustificacion }
    
#ESTADOINFRAESTRUCTURACONTROLLER
MinSalSidPlaReportesBundle_reporteInfraEvaluada:
    pattern:  /reporteInfraEvaluada
    defaults: { _controller: MinSalSidPlaReportesBundle:EstadoInfraestructura:reporteInfraEvaluada }
    
MinSalSidPlaReportesBundle_reporteElementoInfra:
    pattern:  /reporteElementoInfra
    defaults: { _controller: MinSalSidPlaReportesBundle:EstadoInfraestructura:reporteElementoInfra }

#DEFAULTCONTROLLER
MinSalSidPlaReportesBundle_reporteActividadesAtrasadas:
    pattern:  /reporteActividadesAtrasadas
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:reporteActividadesAtrasadas }  
#INFORMACION GERNERAL UNIDAD ORGA    
MinSalSidPlaReportesBundle_reporteInfoGeneral:
    pattern:  /reporteInfoGeneral
    defaults: { _controller: MinSalSidPlaReportesBundle:Admin:reporteInfoGeneral } 
     
MinSalSidPlaReportesBundle_reporteConsolidadoNivelCentral:
    pattern:  /reporteConsolidadoNivelCentral
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:reporteConsolidadoNivelCentral } 
    
MinSalSidPlaReportesBundle_reporteMatrizdeObjetivosyResultados:
    pattern:  /reporteMatrizdeObjetivosyResultados
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:reporteMatrizdeObjetivosyResultados } 


#ACCIONCONSOLIDADOSNIVELCENTRAL
MinSalSidPlaReportesBundle_showConsolidadosNivelCentral:
    pattern:  /showConsolidadosNivelCentral
    defaults: { _controller: MinSalSidPlaReportesBundle:AccionConsolidadosNivelCentral:showConsolidadosNivelCentral } 
    
MinSalSidPlaReportesBundle_reportesUniSal:
    pattern:  /reportesUniSal
    defaults: { _controller: MinSalSidPlaReportesBundle:AccionConsolidadosNivelCentral:reportesUniSal }

MinSalSidPlaReportesBundle_reportesUniSalJSON:
    pattern:  /reportesUniSalJSON
    defaults: { _controller: MinSalSidPlaReportesBundle:AccionConsolidadosNivelCentral:reportesUniSalJSON}
    
MinSalSidPlaReportesBundle_reporteSeleccionadoJSON:
    pattern:  /reporteSeleccionadoJSON
    defaults: { _controller: MinSalSidPlaReportesBundle:AccionConsolidadosNivelCentral:reporteSeleccionadoJSON} 
    
#REPORTE EMPLEADOS DE UNIDADES ORG  
MinSalSidPlaReportesBundle_reporteEmpleadosOrg:
    pattern:  /reporteEmpleadosOrg
    defaults: { _controller: MinSalSidPlaReportesBundle:Admin:reporteEmpleadosOrg}

#COMPROMISO CUMPLIMIENTO
MinSalSidPlaReportesBundle_reporteCompromisoCumplimiento:
    pattern:  /reporteCompromisoCumplimiento
    defaults: { _controller: MinSalSidPlaReportesBundle:ProgramacionMonitoreo:reporteCompromisoCumplimiento}

MinSalSidPlaReportesBundle_reporteCaracOrg:
    pattern:  /reporteCaracOrg
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:reporteCaracOrg } 
    