MinSalSidPlaReportesBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:index }

#PAOCONTROLLER
MinSalSidPlaReportesBundle_reporteJustificacion:
    pattern:  /reportjustificacion
    defaults: { _controller: MinSalSidPlaReportesBundle:Pao:reporteJustificacion }

MinSalSidPlaReportesBundle_reporteIndicadoresSalud:
    pattern:  /reporteIndicadoresSalud
    defaults: { _controller: MinSalSidPlaReportesBundle:Pao:reporteIndicadoresSalud }    
    
    
#ESTADOINFRAESTRUCTURACONTROLLER
MinSalSidPlaReportesBundle_reporteInfraEvaluada:
    pattern:  /reporteInfraEvaluada
    defaults: { _controller: MinSalSidPlaReportesBundle:EstadoInfraestructura:reporteInfraEvaluada }
    
MinSalSidPlaReportesBundle_reporteElementoInfra:
    pattern:  /reporteElementoInfra
    defaults: { _controller: MinSalSidPlaReportesBundle:EstadoInfraestructura:reporteElementoInfra }

#DEFAULTCONTROLLER
MinSalSidPlaReportesBundle_reporteActividadesAtrasadas:
    pattern:  /reporteActividadesAtrasadas
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:reporteActividadesAtrasadas }  

MinSalSidPlaReportesBundle_reporteConsolidadoNivelCentral:
    pattern:  /reporteConsolidadoNivelCentral
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:reporteConsolidadoNivelCentral } 
    
MinSalSidPlaReportesBundle_reporteMatrizdeObjetivosyResultados:
    pattern:  /reporteMatrizdeObjetivosyResultados
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:reporteMatrizdeObjetivosyResultados } 

#INFORMACION GERNERAL UNIDAD ORGA    
MinSalSidPlaReportesBundle_reporteInfoGeneral:
    pattern:  /reporteInfoGeneral
    defaults: { _controller: MinSalSidPlaReportesBundle:Admin:reporteInfoGeneral }

MinSalSidPlaReportesBundle_reporteFormulario1:
    pattern:  /reporteFormulario1
    defaults: { _controller: MinSalSidPlaReportesBundle:Admin:reporteFormulario1 } 
     
MinSalSidPlaReportesBundle_reporteFormulario1Unisal:
    pattern:  /reporteFormulario1Unisal
    defaults: { _controller: MinSalSidPlaReportesBundle:Admin:reporteFormulario1Unisal } 


#ACCIONCONSOLIDADOSNIVELCENTRAL
MinSalSidPlaReportesBundle_showConsolidadosNivelCentral:
    pattern:  /showConsolidadosNivelCentral
    defaults: { _controller: MinSalSidPlaReportesBundle:AccionConsolidadosNivelCentral:showConsolidadosNivelCentral } 
    
MinSalSidPlaReportesBundle_reportesUniSal:
    pattern:  /reportesUniSal
    defaults: { _controller: MinSalSidPlaReportesBundle:AccionConsolidadosNivelCentral:reportesUniSal }

MinSalSidPlaReportesBundle_reportesUniSalJSON:
    pattern:  /reportesUniSalJSON
    defaults: { _controller: MinSalSidPlaReportesBundle:AccionConsolidadosNivelCentral:reportesUniSalJSON}
    
MinSalSidPlaReportesBundle_reportesDepen:
    pattern:  /reportesDepen
    defaults: { _controller: MinSalSidPlaReportesBundle:AccionConsolidadosNivelCentral:reportesDepen }

MinSalSidPlaReportesBundle_reportesDepenJSON:
    pattern:  /reportesDepenJSON
    defaults: { _controller: MinSalSidPlaReportesBundle:AccionConsolidadosNivelCentral:reportesDepenJSON}
    
#REPORTE EMPLEADOS DE UNIDADES ORG  
MinSalSidPlaReportesBundle_reporteEmpleadosOrg:
    pattern:  /reporteEmpleadosOrg
    defaults: { _controller: MinSalSidPlaReportesBundle:Admin:reporteEmpleadosOrg}

#COMPROMISO CUMPLIMIENTO
MinSalSidPlaReportesBundle_reporteCompromisoCumplimiento:
    pattern:  /reporteCompromisoCumplimiento
    defaults: { _controller: MinSalSidPlaReportesBundle:ProgramacionMonitoreo:reporteCompromisoCumplimiento}

MinSalSidPlaReportesBundle_reporteCaracOrg:
    pattern:  /reporteCaracOrg
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:reporteCaracOrg } 

MinSalSidPlaReportesBundle_reporteDependenciaInvidual:
    pattern:  /reporteDependenciaInvidual
    defaults: { _controller: MinSalSidPlaReportesBundle:ProgramacionMonitoreo:reporteDependenciaInvidual } 
    
    