MinSalSidPlaReportesBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:index }
MinSalSidPlaReportesBundle_reporteJustificacion:
    pattern:  /reportjustificacion
    defaults: { _controller: MinSalSidPlaReportesBundle:Default:reporteJustificacion }   
    
