parameters:
#    min_sal_sid_pla_reportes.example.class: MinSal\SidPla\ReportesBundle\Example

services:
#    min_sal_sid_pla_reportes.example:
#        class: %min_sal_sid_pla_reportes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
