parameters:
#    min_sal_sid_pla_admin.example.class: MinSal\SidPla\AdminBundle\Example

services:
#    min_sal_sid_pla_admin.example:
#        class: %min_sal_sid_pla_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
