MinSalSidPlaUsersBundle_mostrarUsuariosSinRol:
    pattern:  /mostrarUsuariosSinRol
    defaults: { _controller: MinSalSidPlaUsersBundle:Default:mostrarUsuariosSinRol}
    
MinSalSidPlaUsersBundle_consultarUsuarioSinRolJSON:
    pattern:  /consultarUsuarioSinRolJSON
    defaults: { _controller: MinSalSidPlaUsersBundle:Default:consultarUsuarioSinRolJSON }
