MinSalSidPlaPrograMonitoreoBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:Default:index }
    
MinSalSidPlaPrograMonitoreoBundle_supervisaUnidades:
    pattern:  /supervisaUnidades
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:Default:supervisaUnidades }

MinSalSidPlaPrograMonitoreoBundle_supervisaUnidadesJSON:
    pattern:  /supervisaUnidadesJSON
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:Default:supervisaUnidadesJSON }


MinSalSidPlaPrograMonitoreoBundle_generarProgramacionJSON:
    pattern:  /generarProgramacionJSON
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionSeguimientoProgramacion:generarProgramacionJSON }

MinSalSidPlaPrograMonitoreoBundle_showProgramacionMonitoreo:
    pattern:  /showProgramacionMonitoreo
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionSeguimientoProgramacion:showProgramacionMonitoreo }


MinSalSidPlaPrograMonitoreoBundle_guardarSegumiento:
    pattern:  /guardarSegumiento
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionSeguimientoProgramacion:guardarSegumiento }

MinSalSidPlaPrograMonitoreoBundle_showActividadesEnRetraso:
    pattern:  /showActividadesEnRetraso
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionCompromisoCumplimiento:showActividadesEnRetraso }
    
MinSalSidPlaPrograMonitoreoBundle_ActividadesEnRetrasoJSON:
    pattern:  /ActividadesEnRetrasoJSON
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionCompromisoCumplimiento:ActividadesEnRetrasoJSON }
#COMPROMISO CUMPLIMIENTO    
MinSalSidPlaPrograMonitoreoBundle_ingresoActividadesEnRetraso:
    pattern:  /ingresoActividadesEnRetraso
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionCompromisoCumplimiento:ingresoActividadesEnRetraso }
    
MinSalSidPlaPrograMonitoreoBundle_guardarActividadesEnRetraso:
    pattern:  /guardarActividadesEnRetraso
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionCompromisoCumplimiento:guardarActividadesEnRetraso }
    
MinSalSidPlaPrograMonitoreoBundle_editandoActividadesEnRetraso:
    pattern:  /editandoActividadesEnRetraso
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionCompromisoCumplimiento:editandoActividadesEnRetraso }
    
MinSalSidPlaPrograMonitoreoBundle_consultarTipoMeta:
    pattern:  /consultarTipoMeta
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionCompromisoCumplimiento:consultarTipoMeta }
MinSalSidPlaPrograMonitoreoBundle_showProgramacionMonitoreoUNISAL:
    pattern:  /showProgramacionMonitoreoUNISAL
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionPrograMonUNISAL:showProgramacionMonitoreoUNISAL }   

MinSalSidPlaPrograMonitoreoBundle_construccionProgramacionMonitoreoUNISAL:
    pattern:  /construccionProgramacionMonitoreoUNISAL
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionPrograMonUNISAL:construccionProgramacionMonitoreoUNISAL }   

MinSalSidPlaPrograMonitoreoBundle_guardarProgramacioUniSal:
    pattern:  /guardarProgramacioUniSal
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionPrograMonUNISAL:guardarProgramacioUniSal }   

MinSalSidPlaPrograMonitoreoBundle_guardarSeguimientoProgramacioUniSal:
    pattern:  /guardarSeguimientoProgramacioUniSal
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionPrograMonUNISAL:guardarSeguimientoProgramacioUniSal }

MinSalSidPlaPrograMonitoreoBundle_supervisarProgramonUnidades:
    pattern:  /supervisarProgramonUnidades
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionUnidadesSupervisadas:supervisarProgramonUnidades }   
   

MinSalSidPlaPrograMonitoreoBundle_showEvaluaciondeResultadosUNISAL:
    pattern:  /showEvaluaciondeResultadosUNISAL
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionEvaluaciondeResultadosUnisal:showEvaluaciondeResultadosUNISAL }   

MinSalSidPlaPrograMonitoreoBundle_guardarEvaluaciondeResultadosUNISAL:
    pattern:  /guardarEvaluaciondeResultadosUNISAL
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionEvaluaciondeResultadosUnisal:guardarEvaluaciondeResultadosUNISAL }   


MinSalSidPlaPrograMonitoreoBundle_supervisarResultadosEspec:
    pattern:  /supervisarResultadosEspec
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionUnidadesSupervisadas:supervisarResultadosEspec }

#SUPERVISADAS POR DIRECCION DE PLANIFICACION
MinSalSidPlaPrograMonitoreoBundle_supervisarProgramonUnidadesXDirPla:
    pattern:  /supervisarProgramonUnidadesXDirPla
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionUnidadesSupervisadas:supervisarProgramonUnidadesXDirPla}
    
MinSalSidPlaPrograMonitoreoBundle_supervisarResultadosEspecXDirPla:
    pattern:  /supervisarResultadosEspecXDirPla
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionUnidadesSupervisadas:supervisarResultadosEspecXDirPla }

