MinSalSidPlaPrograMonitoreoBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:Default:index }

MinSalSidPlaPrograMonitoreoBundle_generarProgramacionJSON:
    pattern:  /generarProgramacionJSON
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionSeguimientoProgramacion:generarProgramacionJSON }

MinSalSidPlaPrograMonitoreoBundle_showProgramacionMonitoreo:
    pattern:  /showProgramacionMonitoreo
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionSeguimientoProgramacion:showProgramacionMonitoreo }


MinSalSidPlaPrograMonitoreoBundle_guardarSegumiento:
    pattern:  /guardarSegumiento
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionSeguimientoProgramacion:guardarSegumiento }

MinSalSidPlaPrograMonitoreoBundle_showActividadesEnRetraso:
    pattern:  /showActividadesEnRetraso
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionCompromisoCumplimiento:showActividadesEnRetraso }
    
MinSalSidPlaPrograMonitoreoBundle_ActividadesEnRetrasoJSON:
    pattern:  /ActividadesEnRetrasoJSON
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionCompromisoCumplimiento:ActividadesEnRetrasoJSON }
    
MinSalSidPlaPrograMonitoreoBundle_ingresoActividadesEnRetraso:
    pattern:  /ingresoActividadesEnRetraso
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionCompromisoCumplimiento:ingresoActividadesEnRetraso }
    
MinSalSidPlaPrograMonitoreoBundle_guardarActividadesEnRetraso:
    pattern:  /guardarActividadesEnRetraso
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionCompromisoCumplimiento:guardarActividadesEnRetraso }
    
MinSalSidPlaPrograMonitoreoBundle_editandoActividadesEnRetraso:
    pattern:  /editandoActividadesEnRetraso
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionCompromisoCumplimiento:editandoActividadesEnRetraso }
    
MinSalSidPlaPrograMonitoreoBundle_consultarTipoMeta:
    pattern:  /consultarTipoMeta
    defaults: { _controller: MinSalSidPlaPrograMonitoreoBundle:AccionCompromisoCumplimiento:consultarTipoMeta }   
    
    