parameters:
#    min_sal_sid_pla_progra_monitoreo.example.class: MinSal\SidPla\PrograMonitoreoBundle\Example

services:
#    min_sal_sid_pla_progra_monitoreo.example:
#        class: %min_sal_sid_pla_progra_monitoreo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
