<?php

namespace MinSal\SidPla\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RolSistemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolSistemaRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM MinSalSidPlaAdminBundle:RolSistema p ORDER BY p.nombreRol ASC')
            ->getResult();
    }
}