MinSalSidPlaEstInfraBundle_principal:
    pattern:  /
    defaults: { _controller: MinSalSidPlaEstInfraBundle:Default:principal }


#Unidad de Medida
MinSalSidPlaEstInfraBundle_consultarUnidadMedidaJSON:
    pattern:  /consultarUnidadMedidaJSON
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraUnidadMedida:consultarUnidadMedidaJSON}

MinSalSidPlaEstInfraBundle_manttUnidadMedida:
    pattern:  /manttUnidadMedida
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraUnidadMedida:manttUnidadMedida}



#elemento infraestructura
MinSalSidPlaEstInfraBundle_consultarElementoInfraestructuraJSON:
    pattern:  /consultarElementoInfraestructuraJSON
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraElementoInfraestructura:consultarElementoInfraestructuraJSON }


MinSalSidPlaEstInfraBundle_manttElementoInfraestrutura:
    pattern:  /manttElementoInfraestrutura
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraElementoInfraestructura:manttElementoInfraestrutura}


#Evaluacion Elemento Infraestructura
MinSalSidPlaEstInfraBundle_mantenimientoEvaluacionElementoInfra:
    pattern:  /mantenimientoEvaluacionElementoInfra
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraEvaluacionElementoInfra:mantenimientoEvaluacionElementoInfra}

MinSalSidPlaEstInfraBundle_consultarEvaluacionElementoJSON:
    pattern:  /consultarEvaluacionElementoJSON
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraEvaluacionElementoInfra:consultarEvaluacionElementoJSON}

MinSalSidPlaEstInfraBundle_manttEvaluacionElemento:
    pattern:  /manttEvaluacionElemento
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraEvaluacionElementoInfra:manttEvaluacionElemento}
    
MinSalSidPlaEstInfraBundle_seleccionaElementos:
    pattern:  /seleccionaElementos
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraEvaluacionElementoInfra:seleccionaElementos }
    
MinSalSidPlaEstInfraBundle_consultarAsignadosJSON:
    pattern:  /consultarAsignadosJSON
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraEvaluacionElementoInfra:consultarAsignadosJSON }

MinSalSidPlaEstInfraBundle_consultarDisponiblesJSON:
    pattern:  /consultarDisponiblesJSON
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraEvaluacionElementoInfra:consultarDisponiblesJSON }
    
MinSalSidPlaEstInfraBundle_manttElemSelec:
    pattern:  /manttElemSelec
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraEvaluacionElementoInfra:manttElemSelec }