MinSalSidPlaEstInfraBundle_principal:
    pattern:  /
    defaults: { _controller: MinSalSidPlaEstInfraBundle:Default:principal }


#Unidad de Medida
MinSalSidPlaEstInfraBundle_consultarUnidadMedidaJSON:
    pattern:  /consultarUnidadMedidaJSON
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraUnidadMedida:consultarUnidadMedidaJSON}

MinSalSidPlaEstInfraBundle_manttUnidadMedida:
    pattern:  /manttUnidadMedida
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraUnidadMedida:manttUnidadMedida}



#elemento infraestructura
MinSalSidPlaEstInfraBundle_consultarElementoInfraestructuraJSON:
    pattern:  /consultarElementoInfraestructuraJSON
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraElementoInfraestructura:consultarElementoInfraestructuraJSON }


MinSalSidPlaEstInfraBundle_manttElementoInfraestrutura:
    pattern:  /manttElementoInfraestrutura
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraElementoInfraestructura:manttElementoInfraestrutura}



