MinSalSidPlaEstInfraBundle_mantenimientoUnidadMedida:
    pattern:  /mantenimientoUnidadMedida
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraUnidadMedida:mantenimientoUnidadMedida }


MinSalSidPlaEstInfraBundle_mantenimientoEvaluacionElementoInfra:
    pattern:  /mantenimientoEvaluacionElementoInfra
    defaults: { _controller: MinSalSidPlaEstInfraBundle:AccionEstInfraEvaluacionElementoInfra:mantenimientoEvaluacionElementoInfra }
