parameters:
#    min_sal_sid_pla_est_infra.example.class: MinSal\SidPla\EstInfraBundle\Example

services:
#    min_sal_sid_pla_est_infra.example:
#        class: %min_sal_sid_pla_est_infra.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
