#Routing de RRMedicoBundle
MinSalSidPlaRRMedicoBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MinSalSidPlaRRMedicoBundle:Default:index }


#TipoHorario
MinSalSidPlaRRMedicoBundle_consultarTipoHorarioJSON:
    pattern:  /consultarTipoHorarioJSON
    defaults: { _controller: MinSalSidPlaRRMedicoBundle:AccionRRMedicoTipoHorario:consultarTipoHorarioJSON }

MinSalSidPlaRRMedicoBundle_manttTipoHorario:
    pattern:  /manttTipoHorario
    defaults: { _controller: MinSalSidPlaRRMedicoBundle:AccionRRMedicoTipoHorario:manttTipoHorario }

MinSalSidPlaRRMedicoBundle_consultarTipoHorario:
    pattern:  /consultarTipoHorario
    defaults: { _controller: MinSalSidPlaRRMedicoBundle:AccionRRMedicoTipoHorario:consultarTipoHorario}


#ResulPrograRRMed
MinSalSidPlaRRMedicoBundle_consultarResulPrograRRMed:
    pattern:  /consultarResulPrograRRMed
    defaults: { _controller: MinSalSidPlaRRMedicoBundle:AccionRRMedicoResulPrograRRMed:consultarResulPrograRRMed}
MinSalSidPlaRRMedicoBundle_consultarResulPrograRRMedJSON:
    pattern:  /consultarResulPrograRRMedJSON
    defaults: { _controller: MinSalSidPlaRRMedicoBundle:AccionRRMedicoResulPrograRRMed:consultarResulPrograRRMedJSON}
