MinSalSidPlaPaoBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaPaoBundle:Default:index }

#PARA PERIODO PAO
MinSalSidPlaPaoBundle_mantenimientoPeriodoOficial:
    pattern:  / mantenimientoPeriodoOficial
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoPeriodoOficial:mantenimientoPeriodoOficial }

MinSalSidPlaPaoBundle_mantenimientoTipoPeriodo:
    pattern:  /mantenimientoTipoPeriodo
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoTipoPeriodo:mantenimientoTipoPeriodo }
    
MinSalSidPlaPaoBundle_consultarTipoPeriodoJSON:
    pattern:  /consultarTipoPeriodoJSON
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoTipoPeriodo:consultarTipoPeriodoJSON}
    
MinSalSidPlaPaoBundle_ingresarTipoPeriodo:
    pattern:  /ingresarTipoPeriodo
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoTipoPeriodo:ingresarTipoPeriodo}  
    
MinSalSidPlaPaoBundle_addTipoPeriodo:
    pattern:  /addTipoPeriodo
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoTipoPeriodo:addTipoPeriodo}  

#PARA JUSTIFICACION
MinSalSidPlaPaoBundle_manttJustificacion:
    pattern:  /manttJustificacion
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionJustificacion:manttJustificacion }

#Le agregue esta linea porque sino me tronaba la aplicacion
MinSalSidPlaPaoBundle_consultarJustificacion:
    pattern:  /consultarJustificacion
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionJustificacion:consultarJustificacion }