MinSalSidPlaPaoBundle_homepage:
    pattern:  /Pao/
    defaults: { _controller: MinSalSidPlaPaoBundle:Default:index }
    
MinSalSidPlaPaoBundle_mantenimientoPeriodoOficial:
    pattern:  /Pao/mantenimientoPeriodoOficial
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoPeriodoOficial:mantenimientoPeriodoOficial }
