#ROUTING DEL PAOBUNDLE
MinSalSidPlaPaoBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaPaoBundle:Default:index }

#PARA TIPO PERIODO
MinSalSidPlaPaoBundle_mantenimientoTipoPeriodo:
    pattern:  /mantenimientoTipoPeriodo
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoTipoPeriodo:mantenimientoTipoPeriodo }
    
MinSalSidPlaPaoBundle_consultarTipoPeriodoJSON:
    pattern:  /consultarTipoPeriodoJSON
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoTipoPeriodo:consultarTipoPeriodoJSON}

MinSalSidPlaPaoBundle_manttTipoPeriodo:
    pattern:  /manttTipoPeriodo
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoTipoPeriodo:manttTipoPeriodo }
    
MinSalSidPlaPaoBundle_consultarPeriodoOficialJSON:
    pattern:  /consultarPeriodoOficialJSON
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoPeriodoOficial:consultarPeriodoOficialJSON }
    
MinSalSidPlaPaoBundle_manttPeriodoOficial:
    pattern:  /manttPeriodoOficial
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoPeriodoOficial:manttPeriodoOficial }
    
#PARA PERIODO PAO
MinSalSidPlaPaoBundle_mantenimientoPeriodoPao:
    pattern:  /mantenimientoPeriodoPao
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoPeriodoPao:mantenimientoPeriodoPao  }
    
MinSalSidPlaPaoBundle_consultarPeriodoPaoJSON:
    pattern:  /consultarPeriodoPaoJSON
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoPeriodoPao:consultarPeriodoPaoJSON  }
    
MinSalSidPlaPaoBundle_manttPeriodoPao:
    pattern:  /manttPeriodoPao
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoPeriodoPao:manttPeriodoPao }    
    

#PARA JUSTIFICACION    
MinSalSidPlaPaoBundle_consultarJustificacion:
    pattern:  /consultarJustificacion
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionJustificacion:consultarJustificacion }
    
MinSalSidPlaPaoBundle_consultarJustificacionJSON:
    pattern:  /consultarJustificacionJSON
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionJustificacion:consultarJustificacionJSON }   
    
MinSalSidPlaPaoBundle_manttJustificacionEdicion:
    pattern:  /manttJustificacionEdicion    
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionJustificacion:manttJustificacionEdicion }

MinSalSidPlaPaoBundle_actualizarJustificacion:
    pattern:  /actualizarJustificacion    
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionJustificacion:actualizarJustificacion }

MinSalSidPlaPaoBundle_reporteJustificacion:
    pattern:  /reporteJustificacion    
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionJustificacion:reporteJustificacion }

