MinSalSidPlaPaoBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaPaoBundle:Default:index }

#PARA PERIODO PAO
MinSalSidPlaPaoBundle_mantenimientoPeriodoOficial:
    pattern:  / mantenimientoPeriodoOficial
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoPeriodoOficial:mantenimientoPeriodoOficial }

MinSalSidPlaPaoBundle_mantenimientoTipoPeriodo:
    pattern:  /mantenimientoTipoPeriodo
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoTipoPeriodo:mantenimientoTipoPeriodo }
    
MinSalSidPlaPaoBundle_consultarTipoPeriodoJSON:
    pattern:  /consultarTipoPeriodoJSON
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoTipoPeriodo:consultarTipoPeriodoJSON}
    
MinSalSidPlaPaoBundle_ingresarTipoPeriodo:
    pattern:  /ingresarTipoPeriodo
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoTipoPeriodo:ingresarTipoPeriodo}  
    
MinSalSidPlaPaoBundle_addTipoPeriodo:
    pattern:  /addTipoPeriodo
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionPaoTipoPeriodo:addTipoPeriodo}  
    
MinSalSidPlaPaoBundle_consultarJustificacion:
    pattern:  /consultarJustificacion
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionJustificacion:consultarJustificacion }
    
MinSalSidPlaPaoBundle_consultarJustificacionJSON:
    pattern:  /consultarJustificacionJSON
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionJustificacion:consultarJustificacionJSON }   
    
MinSalSidPlaPaoBundle_manttJustificacionEdicion:
    pattern:  /manttJustificacionEdicion    
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionJustificacion:manttJustificacionEdicion }

MinSalSidPlaPaoBundle_actualizarJustificacion:
    pattern:  /actualizarJustificacion    
    defaults: { _controller: MinSalSidPlaPaoBundle:AccionJustificacion:actualizarJustificacion }
