parameters:
#    min_sal_sid_pla_pao.example.class: MinSal\SidPla\PaoBundle\Example

services:
#    min_sal_sid_pla_pao.example:
#        class: %min_sal_sid_pla_pao.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
