MinSalSidPlaCensoBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaCensoBundle:Default:index }

MinSalSidPlaCensoBundle_consultarBloqueCenso:
    pattern:  /consultarBloqueCenso    
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminBloque:consultarBloqueCenso }

MinSalSidPlaCensoBundle_consultarBloqueCensoJSON:
    pattern:  /consultarBloqueCensoJSON    
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminBloque:consultarBloqueCensoJSON }   
    
MinSalSidPlaCensoBundle_manttBloqueCensoEdicion:
    pattern:  /manttBloqueCensoEdicion
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminBloque:manttBloqueCensoEdicion }
