#ROUTING DEL CENSOBUNDLE
MinSalSidPlaCensoBundle_homepage:
    pattern:  /
    defaults: { _controller: MinSalSidPlaCensoBundle:Default:index }
    
MinSalSidPlaCensoBundle_manttCatCenso:
    pattern:  /manttCensoPoblacion
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminCategoriaCenso:manttCatCenso }
    
MinSalSidPlaCensoBundle_consultarCategoriaCensoJSON:
    pattern:  /consultarCategoriaCensoJSON
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminCategoriaCenso:consultarCategoriaCensoJSON }

MinSalSidPlaCensoBundle_ingresarCategoriaForm:
    pattern:  /ingresarCategoriaForm
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminCategoriaCenso:ingresarCategoriaForm }

MinSalSidPlaCensoBundle_addCategoria:
    pattern:  /addCategoria
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminCategoriaCenso:addCategoria }
    
MinSalSidPlaCensoBundle_consultarBloqueCenso:
    pattern:  /consultarBloqueCenso    
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminBloque:consultarBloqueCenso }

MinSalSidPlaCensoBundle_consultarBloqueCensoJSON:
    pattern:  /consultarBloqueCensoJSON    
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminBloque:consultarBloqueCensoJSON }   
    
MinSalSidPlaCensoBundle_manttBloqueCensoEdicion:
    pattern:  /manttBloqueCensoEdicion
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminBloque:manttBloqueCensoEdicion }
    
MinSalSidPlaCensoBundle_consultarInformacionComplementaria:
    pattern:  /consultarInformacionComplementaria    
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminCensoUsuario:consultarInformacionComplementaria }

MinSalSidPlaCensoBundle_consultarInformacionComplementariaJSON:
    pattern:  /consultarInformacionComplementariaJSON   
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminCensoUsuario:consultarInformacionComplementariaJSON}   
    
MinSalSidPlaCensoBundle_manttInformacionComplementariaEdicion:
    pattern:  /manttInformacionComplementariaEdicion
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminCensoUsuario:manttInformacionComplementariaEdicion }


MinSalSidPlaCensoBundle_consultarPoblacionHumanaJSON:
    pattern:  /consultarPoblacionHumanaJSON   
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminCensoUsuario:consultarPoblacionHumanaJSON }   
    
MinSalSidPlaCensoBundle_manttPoblacionHumanaEdicion:
    pattern:  /manttPoblacionHumanaEdicion
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminCensoUsuario:manttPoblacionHumanaEdicion }

MinSalSidPlaCensoBundle_consultarCategoriaCensoUsuarioJSON:
    pattern:  /consultarCategoriaCensoUsuarioJSON
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminCensoUsuario:consultarCategoriaCensoUsuarioJSON }
   
MinSalSidPlaCensoBundle_consultarInformacionRelevanteJSON:
    pattern:  /consultarInformacionRelevanteJSON
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminCensoUsuario:consultarInformacionRelevanteJSON }

MinSalSidPlaCensoBundle_consultarDatosCategoriaJSON:
    pattern:  /consultarDatosCategoriaJSON
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminCensoUsuario:consultarDatosCategoriaJSON }
    
MinSalSidPlaCensoBundle_ingresarPoblacionHumana:
    pattern:  /ingresarPoblacionHumana
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminCensoUsuario:ingresarPoblacionHumana }
    
MinSalSidPlaCensoBundle_ingresarInfReleva:
    pattern:  /ingresarInfReleva
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminCensoUsuario:ingresarInfReleva }

MinSalSidPlaCensoBundle_procesarPoblacionHumana:
    pattern:  /procesarPoblacionHumana
    defaults: { _controller: MinSalSidPlaCensoBundle:AccionAdminCensoUsuario:procesarPoblacionHumana }

 
    
    
    