parameters:
#    min_sal_sid_pla_censo.example.class: MinSal\SidPla\CensoBundle\Example

services:
#    min_sal_sid_pla_censo.example:
#        class: %min_sal_sid_pla_censo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
